name: 'Download Artifacts'
description: ''
inputs:
  run_number:
    description: 'package version'
    required: true
    default: ''
outputs:
  Version-number:
    description: "Nuget Version Number from build.txt"
    value: ${{ steps.versionsetup.outputs.NugetVersion }}
runs:
  using: "composite"
  steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ github.token }}
        workflow: ci-build-dev.yml
        workflow_conclusion: ""  #Only pick the last successful run.
        name: build.txt
        path: ${{ github.workspace }}
        if_no_artifact_found: fail
    - name: List
      shell: pwsh
      run: ls ${{ github.workspace }}
    - name: BUILD version
      shell: pwsh
      run: Get-Content -Path build.txt
    - name: Setting up the Nuget Version
      id: versionsetup
      shell: pwsh
      run: |
        $buildnumber = Get-Content -Path build.txt
        echo $buildnumber
        echo "::set-output name=NugetVersion::$buildnumber"
    - name: Nuget version
      shell: pwsh
      run: echo ${{ steps.versionsetup.outputs.NugetVersion}}
      
    # - name: Add private GitHub registry to NuGet
    #   shell: pwsh
    #   run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }}
    
    # - name: Installing Web package from GitHub Nuget registry
    #   shell: pwsh
    #   run: |
    #     nuget install Ucare.web -source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -OutputDirectory ${{ github.workspace }} -Version ${{ steps.versionsetup.outputs.NugetVersion}}

    # - name: Installing TDS package from GitHub Nuget registry
    #   shell: pwsh
    #   run: |
    #     nuget install Ucaresc-package -source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -OutputDirectory ${{ github.workspace }} -Version ${{ steps.versionsetup.outputs.NugetVersion}}

    # - name: List
    #   shell: pwsh
    #   run: ls ${{ github.workspace }}