name: 'Common Build Action'
description: ''
inputs:
  PackageName:
    description: 'Name of the package'
    required: true
    default: ''
  Version_Full:
    description: 'Version number'
    required: true
    default: '' 
  OutputDirectory:
    description: 'Output Directory where your build artifacts will be stored'
    required: true
    default: '' 
runs:
  using: "composite"
  steps:
    - name: list files
      run: dir ${{ github.workspace }}
      shell: pwsh
    
    - name: Create Web Nuget Package
      shell: pwsh
      working-directory: ${{ github.workspace }}\deploy\Sitecore.Deployment\build\scripts
      run: |
        ./CreateNupkgfromdirectory.ps1 -PackageName ${{ inputs.PackageName }} -OutputDirectory "${{ github.workspace }}\deploy\workdir" -InputDirectory "${{ inputs.OutputDirectory }}" -Version "${{ inputs.Version_Full }}"
    
    - name: list files
      run: dir ${{ github.workspace }}\deploy\workdir
      shell: pwsh

    # - name: Publishing Package Number
    #   shell: pwsh
    #   run: |
    #     Set-Content -Path ${{ github.workspace }}\deploy\artifacts\build.txt -Value "${{ inputs.Version_Full }}"
    
    # - name: Add private GitHub registry to NuGet
    #   shell: pwsh
    #   run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }}
    
    # - name: Push generated package to GitHub registry
    #   shell: pwsh
    #   run: |
    #     dotnet nuget push ${{ github.workspace }}\deploy\artifacts\Ucare.web.*.nupkg --api-key ${{ github.token }} --source github
    #     dotnet nuget push ${{ github.workspace }}\deploy\artifacts\Ucaresc-package.*.nupkg --api-key ${{ github.token }} --source github
    # # - uses: actions/upload-artifact@v3
    # #   with:
    # #     name: ${{ inputs.PackageName }}-${{ inputs.Version_Full }}
    # #     path: ${{ github.workspace }}\deploy\artifacts\*.nupkg
    
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: build.txt
    #     path: ${{ github.workspace }}\deploy\artifacts\build.txt