name: 'Download Artifacts'
description: ''
inputs:
  nuget_version:
    description: 'package version'
    required: true
    default: ''
  SCSPackageName:
    description: 'SCS package name'
    required: true
    default: ''
  PackageName:
    description: 'Web Package name'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Get the Version of build to extract itempackage
      id: getbuildversion
      shell: pwsh
      run: |
        $build_number = ${{ inputs.nuget_version }}.split('.')[2]
        echo "::set-output name=build_number::$build_number"
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ github.token }}
        workflow: ci-build-dev.yml
        workflow_conclusion: success  #Only pick the last successful run.Will ignore latest failed runs.  
        name: ${{ inputs.SCSPackageName }}
        run_number: ${{ steps.getbuildversion.outputs.build_number}}
        path: ${{ github.workspace }}
        if_no_artifact_found: fail
    - name: Add private GitHub registry to NuGet
      shell: pwsh
      run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }}
    
    - name: Installing Web package from GitHub Nuget registry
      shell: pwsh
      run: |
        nuget install ${{ inputs.PackageName }} -source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -OutputDirectory ${{ github.workspace }} -Version ${{ inputs.nuget_version }}

    - name: List
      shell: pwsh
      run: ls ${{ github.workspace }}