name: Build

on:
  push:
    branches: [ "main" ]

env:
  Version_Full: 0.0.${{github.run_number}}
  SolutionfileName: Neptune.sln
  PackageName: Neptune.web
  OutputDirectory: ${{ github.workspace }}\deploy\artifacts
  SCSPackageName: NeptuneSerialization
  Sitecore_CM_Url: test-neptune-cm.azurewebsites.net
  Sitecore_CD_Url: test-neptune-cd.azurewebsites.net

jobs:
  devbuild:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Initiate build action
      uses: ./.github/actions/build-action/
      with:
        SolutionfileName: ${{ env.SolutionfileName }}
        Version_Full: ${{ env.Version_Full }}
    - name: Initiate common action
      uses: ./.github/actions/common-build-action/
      with:
        PackageName: ${{env.PackageName}}
        Version_Full: ${{ env.Version_Full }}
        OutputDirectory: ${{ env.OutputDirectory }}
        SCSPackageName: ${{ env.SCSPackageName }}
        Sitecore_CM_Url: ${{ env.Sitecore_CM_Url }}
        Sitecore_CD_Url: ${{ env.Sitecore_CD_Url }}



  