name: Release

on:
  workflow_dispatch:
    inputs:
      run_number:
        description: 'Package Version'
        required: true
        default: 'latest'
      SCSPackageName: 
        description: 'Name of the serialisation Item Package'
        required: true
        default: 'NeptuneSerialization.itempackage'
      PackageName:
        description: 'Name of the Web Package'
        required: true
        default: 'Neptune.web'


jobs:
  GetArtifacts:
    uses: ./.github/workflows/get-version.yml
    with:
      run_number: ${{ github.event.inputs.run_number }}
  DEV-CM:
    uses: ./.github/workflows/ci-release-template-cm.yml
    needs: GetArtifacts
    with:
      nuget_version: ${{ needs.GetArtifacts.outputs.version_number }}
      SCSPackageName: ${{ github.event.inputs.SCSPackageName }}
      PackageName: ${{ github.event.inputs.PackageName}}
      environment: DEV-CM
      webapp-name: "test-neptune-cm"
      webapp-type: "cm"
      resource-group-name: "neptune"
      cm-url: "https://test-neptune-cm.azurewebsites.net/"
      identity-url: "https://test-neptune-si.azurewebsites.net/"
      sitecore-clientID: "SitecoreCLIServer"
      sitecore-clientSecret: "O1GS2BIT96A9CL73NY5GMACH53JEO1Y"
      ClientName: Neptune
  DEV-CD:
    uses: ./.github/workflows/ci-release-template-cd.yml
    needs: DEV-CM
    with:
      nuget_version: ${{ needs.GetArtifacts.outputs.version_number }}
      PackageName: ${{ github.event.inputs.PackageName}}
      environment: DEV-CD
      webapp-name: "test-neptune-cd"
      webapp-type: "cd"
      resource-group-name: "neptune"
      cm-url: "https://test-neptune-cm.azurewebsites.net/"
      cd-url: "https://test-neptune-cd.azurewebsites.net/"
      identity-url: "https://test-neptune-si.azurewebsites.net/"
      sitecore-clientID: "SitecoreCLIServer"
      sitecore-clientSecret: "O1GS2BIT96A9CL73NY5GMACH53JEO1Y"
      ClientName: Neptune
      