name: Release

on:
  workflow_dispatch:
    inputs:
      run_number:
        description: 'Package Version'
        required: true
        default: 'latest'

jobs:
  GetArtifacts:
    uses: ./.github/workflows/get-version.yml
    with:
      run_number: ${{ github.event.inputs.run_number }}
  DEV-CM:
    uses: ./.github/workflows/ci-release-template-cm.yml
    needs: GetArtifacts
    with:
      run_number: ${{ needs.GetArtifacts.outputs.version_number }}
  #   with:
  #     environment: DEV-CM
  # DEV-CD:
  #   uses: ./.github/workflows/ci-release-template-cd.yml
  #   needs: GetArtifacts
  #   with:
  #     environment: DEV-CD