name: Release

on:
  workflow_dispatch:
    inputs:
      run_number:
        description: 'Package Version'
        required: true
        default: 'latest'
      SCSPackageName: 
        description: 'Name of the serialisation Item Package'
        required: true
        default: 'NeptuneSerialization.itempackage'
      PackageName:
        description: 'Name of the Web Package'
        required: true
        default: 'Neptune.web'


jobs:
  GetArtifacts:
    uses: ./.github/workflows/get-version.yml
    with:
      run_number: ${{ github.event.inputs.run_number }}
  DEV-CM:
    uses: ./.github/workflows/ci-release-template-cm.yml
    needs: GetArtifacts
    with:
      nuget_version: ${{ needs.GetArtifacts.outputs.version_number }}
      SCSPackageName: ${{ github.event.inputs.SCSPackageName }}
      PackageName: ${{ github.event.inputs.PackageName}}
      environment: DEV-CM
  DEV-CD:
    uses: ./.github/workflows/ci-release-template-cm.yml
    needs: GetArtifacts
    with:
      nuget_version: ${{ needs.GetArtifacts.outputs.version_number }}
      SCSPackageName: ${{ github.event.inputs.SCSPackageName }}
      PackageName: ${{ github.event.inputs.PackageName}}
      environment: DEV-CM
      