name: Release

on:
  workflow_dispatch:
    inputs:
      run_number:
        description: 'Package Version'
        required: true
        default: 'latest'

jobs:
  GetArtifacts:
    uses: ./.github/workflows/download-artifacts.yml
    with:
      run_number: ${{ github.event.inputs.run_number }}
  # MySecondJob:
  #   runs-on: windows-latest
  #   needs: GetArtifacts
  #   steps:
  #   - uses: actions/checkout@v3
  #   - run: echo ${{ needs.GetArtifacts.outputs.version_number }}
  #     shell: pwsh
  DEV-CM:
    uses: ./.github/workflows/ci-release-template-cm.yml
    needs: GetArtifacts
    with:
      run_number: ${{ needs.GetArtifacts.outputs.version_number }}
  #   with:
  #     environment: DEV-CM
  # DEV-CD:
  #   uses: ./.github/workflows/ci-release-template-cd.yml
  #   needs: GetArtifacts
  #   with:
  #     environment: DEV-CD