name: Download Artifacts

on:
  workflow_call:
    inputs:
      run_number:
        required: true
        type: string
    outputs:
      version_number:
        description: "Version number reteived from"
        value: ${{ jobs.retrieve-version.outputs.Version-number }}

jobs:
  retrieve-version:
    name: Retrieve Version
    runs-on: windows-latest
    outputs:
      Version-number: ${{ steps.retrieve-version.outputs.Version-number }}
    steps:
    - uses: actions/checkout@v3
    - name: Download Latest Build Artifacts
      id: retrieve-version
      uses: ./.github/actions/retrieve-latest-version/
      with:
        run_number: ${{ inputs.run_number }}
      if: ${{ inputs.run_number == 'latest' }}
    - name: Download Specific Build Artifacts
      id: retrieve-version
      uses: ./.github/actions/retrieve-specific-version/
      with:
        run_number: ${{ inputs.run_number }}
      if: ${{ inputs.run_number != 'latest' }}